### ISSUE TITLE
WINSOCK2 topic 

### ISSUE THREAD

**Issue by zerubeus** [Ybalrid/virtual-air-hockey#13]
A topic to discuss all related WINSOCK2 stuff , and every commit that have a relation with winsock2 will have the Htag of this Issue !

**Comment by zerubeus** [comment]
what's already done : 
- Client device. In a client/server game, the player uses the client device.
- Running the game. The server typically runs the game.
- TCP. Transmission control protocol (TCP) provides reliable delivery of data.
- UDP. User datagram protocol (UDP) does not guarantee the delivery of data.
- Winsock. Winsock is Microsoft’s socket API for Windows.
- Initiation of Winsock. Winsock’s WSAStartup function initiates the use of Winsock.
- Creating a socket. Winsock’s socket function creates a socket.
- Nonblocking mode. Winsock’s ioctlsocket function may be used to put a socket
  in nonblocking mode.
- Creating a server. The Net::createServer function may be used to create a
  UDP or TCP server.
- Connecting sockets with addresses. Winsock’s bind function associates a socket
  with an address.
- Bound sockets. Only bound sockets may listen for incoming connections.
- Creating a client. The Net::createClient function may be used to create a UDP
  or TCP client.
- Returning IP addresses. Winsock’s getaddrinfo function returns the IP address
  of a host name.
- Returning the host name. Winsock’s gethostname function returns the host name
  of the local computer.
- Sending data. The Net class’s sendData function sends data to the specified IP
  address.
- Connection between sockets. Winsock’s connect function establishes a connection
  between TCP sockets.
- Socket to socket. Winsock’s sendto function sends data from socket to socket.
- Reading network data. The Net::readData function reads network data.
- TCP server socket configuration. Winsock’s listen function configures a TCP
  server socket to wait for incoming connections.
- Creating a new socket. Winsock’s accept function creates a new socket that is connected
  to an incoming connection.
- Reading data. Winsock’s recvfrom reads data from the network.
- Closing and releasing. The Net::closeSocket function closes a socket and releases
  its resources.
- Closing a socket. Winsock’s closesocket function closes a socket.
- Deregistering. Winsock’s WSACleanup function deregisters an application from
  Windows sockets.
- Error messages. The Net::getError function returns a detailed error message
  from a two-part error code.
- Bandwidth requirements. The bandwidth requirements of a game server increase by
  the number of players squared.
- State changes. Using state changes is a more reliable way to send momentary data
  on a UDP network.

**Comment by Ybalrid** [comment]
So, to accomodate both TCP and UDP we have a client/server architecture that isn't dependent of the protocol. (even if as of now we only used UDP)
The only "fixed" thing is that "Server" means "Player One" and Client "Player Two". 

We have two classes "_NetworkServer_" and "_NetworkClient_" that shares a lot of code (they are mostly equivalent) and that derivate from the same "_NetworkWorker_" class. It uses a thin object-oriented wraper (the Net class you allready described) around Winsock2 just to make things easier and more C++ freindly. 

It worked as planed, exept that processing network data at the speed of the game's main loop wasn't enough. It seems that packet data were piling up on the socket and this introducend unecessary latnecy that increased during the game execution. (only one packet, and not the most recent, was took into account at each "network update"

The simple workaround was do go async: 
- The Network code is run whenever NetworkWorker::update() is called (it send/get the packets with up to date information and gives a nice interface with a few methods that the Gameplay code can use really easily). 
- The class follow a classic design pattern "singleton" so the single instance of the Network is accesible from everywhere, and can be used by the level's gameplay code. This is super nice because it doesn't require to give the gameplay code a pointer/reference to the NetworkWorker object.
- We spawn a thread that will by itself call NetworkWorker::update() in an infinite loop to process every packet as fast as possible. It may still need some testing but it seems that the problem is gone. (awesome)

The network transmit the raw content of a struct to the network. the structure contains at least a UCHAR and a AnnVect3 object, and it's size is know in advance. This data lives on the stack. The projects is specifically compiled to have 1 byte memory padding for the structs.

The game doesn't actually uses a "state change" architecture si it wasn't really needed. it's actually sending 3D coordinates over the network as fast as possible.
